JavaScript & NodeJS parsers
serpapi/code-challenge pull request #43
Opened 2020-12-19 08:44 UTC by Mykhailo-Zub

I made a parser using Front-end JavaScript and another parser using NodeJS

2020-12-22 16:27 UTC, ilyazub requested changes
Thanks, @Mykhailo-Zub! Good job on trying out Node.js and implementing parser by using it. And thanks for including your initial browser-based solution :+1: 

An implementation in `resultNodeJS/index.js` and tests for it have several flaws I'd like to address.

2020-12-22 16:27 UTC, ilyazub commented on resultNodeJS/index.js
> +                console.log(`File ${fileName}.json created successful!`);
Writing results to file could be extracted to separate function to not mess up tests. Also parsing and writing results to file are different operations. But for now, that's fine.

![image](https://user-images.githubusercontent.com/282605/102909690-07aabf80-4482-11eb-9217-7db00ebe2357.png)
![image](https://user-images.githubusercontent.com/282605/102909747-1d1fe980-4482-11eb-9c2f-c03585a39651.png)

2020-12-22 16:27 UTC, ilyazub commented on resultNodeJS/index.js
> +    return imgLinks;
How this can be simplified and reduced to the several lines of code? Seems like a good candidate to use regular expressions.

2020-12-22 16:48 UTC, ilyazub commented
Also, it'd be great to have some convenient script to execute the parser against HTML file instead of doing it manually.

```bash
node -e "const { parseHtml } = require('./resultNodeJS/index.js'); parseHtml('./files/jason-statham-movies.html').then(r => console.log(JSON.stringify(r, null, 2)))"
```

➜

```bash
node ./resultNodeJS/parse.js ./files/jason-statham-movies.html
```

2020-12-24 20:16 UTC, Mykhailo-Zub commented on resultNodeJS/index.js
> +    } else console.error("Can't find Google Carousel!");
Fixed.

2020-12-24 20:16 UTC, Mykhailo-Zub commented on resultNodeJS/index.test.js
> +});
Fixed.

2020-12-24 20:16 UTC, Mykhailo-Zub commented on resultNodeJS/index.js
> +                console.log(`File ${fileName}.json created successful!`);
Fixed.

2020-12-24 20:17 UTC, Mykhailo-Zub commented on resultNodeJS/index.js
> +    return imgLinks;
Fixed.

2020-12-24 20:20 UTC, Mykhailo-Zub commented
> Also, it'd be great to have some convenient script to execute the parser against HTML file instead of doing it manually.
> 
> ```shell
> node -e "const { parseHtml } = require('./resultNodeJS/index.js'); parseHtml('./files/jason-statham-movies.html').then(r => console.log(JSON.stringify(r, null, 2)))"
> ```
> 
> ➜
> 
> ```shell
> node ./resultNodeJS/parse.js ./files/jason-statham-movies.html
> ```

Fixed. Now you can run my parser using for example "npm start  ./files/jason-statham-movies.html"

2021-03-01 15:08 UTC, closed without merging