Sebastian's solution
serpapi/code-challenge pull request #87
Opened 2022-08-12 02:56 UTC by sebastianquek

## Setup
* Ensure you have node on your machine (v14 or later)
* Run the following:
```bash
npm i
npm test
```

## Notes
- Relies on TypeScript, Jest and Cheerio
- Main files to look at are `src/scrape-google-carousel.ts` and `src/__tests__/scrape-google-carousel.test.ts`
- 2 additional test files are added (`files/leonardo-da-vinci-art.html` and `files/top-cyclists.html`)

## Future improvements
Given the time constraints, there are a couple of things that can possibly be explored.
- Better test the links and images to avoid flakey tests when a new html is generated
- Figure out a better way to decode the image URIs, i.e. `\x3d` -> `=`
- Perform requests to actual search URLs

2022-08-12 11:44 UTC, aciddjus requested changes
Thank you, Sebastian. 💯 

Realy interesting solution using TypeScrip. And great job on adding tests and new HTMLs.

I just have a few remarks:

----------------------------

Currently, the tests are failing:

![image](https://user-images.githubusercontent.com/6929257/184344980-ce1a1e62-9a1c-43f2-bc71-b08a159d6e29.png)

![image](https://user-images.githubusercontent.com/6929257/184345013-9bae11ad-3dc6-41c4-88aa-755feaafc75d.png)

2022-08-12 11:44 UTC, aciddjus commented on src/scrape-google-carousel.ts
> +  private getImage(element: cheerio.Element): string | null {
What about extracting images that are hidden on the initial page load:

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/6929257/184345684-6a0c64c9-3f62-4bea-bc8d-036d773b224f.png">

Your current implementation returns `null`

![image](https://user-images.githubusercontent.com/6929257/184345905-3b90ddd6-d14a-44d4-8b8e-3049f745e714.png)

Would you be able to update your code to extract those as well?

2022-08-25 06:46 UTC, sebastianquek commented on src/scrape-google-carousel.ts
> +  private getImage(element: cheerio.Element): string | null {
Thanks for your patience, just got back from vacation and have worked on the changes.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/577802/186593940-6b935de4-603c-4e83-916b-9504a1e5dc81.png">

The image URIs are extracted via the target anchor element's id.

2022-08-25 07:07 UTC, sebastianquek commented
While I was debugging the image issue, I noticed a couple of regressions on the playground,

1. Name of first artwork isn't appearing (i.e. "Mona Lisa")
2. Multi-line names are not appearing correctly (i.e. "The Last Supper")

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/577802/186597533-4d32057d-6284-4ec0-b3b7-22c153cfc784.png">

https://serpapi.com/searches/2a4ab588f281c6f4/6306e8aafe41d0b5d036d61c.json

Should I raise an issue here: https://github.com/serpapi/public-roadmap/issues?

2022-08-25 22:58 UTC, hartator commented
> Should I raise an issue here: https://github.com/serpapi/public-roadmap/issues?

Yes, that will be great. We will address these. Thank you @sebastianquek. 👍

2022-09-02 19:31 UTC, ilyazub reviewed
:+1:

2022-09-02 19:31 UTC, ilyazub commented on src/utils.ts
> +};
:+1:

Usually this is handled with `str.replace(/* ... */)`, but you approach looks fine.

2022-09-02 19:31 UTC, ilyazub commented on src/scrape-google-carousel.ts
> +      const parsedInnerHtml = cheerio.load(hexToAscii(targetInnerHtml));
Good job on decoding and unescaping HTML.

2022-10-04 01:29 UTC, closed without merging